Списки:

In [1]:
animals = ['кошка', 'собака', 'хомяк', 'морская свинка', 'попугай', 'лошадь']
print(animals[0])
print(animals[2])
print(animals[3])

кошка
хомяк
морская свинка


In [2]:
animals = ['кошка', 'собака', 'хомяк', 'морская свинка', 'попугай', 'лошадь']
print(animals[-1])
print(animals[-2])
print(animals[-6])

лошадь
попугай
кошка


In [ ]:
OurBestStudents = ['Александр', 'Константин', 'Мария', 'Диана', 'Алексей', 
                   'Максим', 'Светлана', 'Арина', 'Серафим', 'Doomer', 
                   'Павел', 'Виктория', 'Елена', 'Галина', 'Вячеслав']

Срезы:

In [8]:
colors = ['красный', 'оранжевый', 'жёлтый', 'зелёный', 'голубой', 'синий', 'фиолетовый']
print(colors[1:4])
print()
print(colors[2:5])
print(colors[2:-2])
print(colors[-5:5])
print()
print(colors[-3:])        #не указываем верхнюю границу для включения последнего элемента списка в срез
print(colors[:3])         #не указываем нижнюю границу для включения первого элемента списка в срез

['оранжевый', 'жёлтый', 'зелёный']

['жёлтый', 'зелёный', 'голубой']
['жёлтый', 'зелёный', 'голубой']
['жёлтый', 'зелёный', 'голубой']

['голубой', 'синий', 'фиолетовый']
['красный', 'оранжевый', 'жёлтый']


In [21]:
body = ['голова', 'руки', 'ноги', 'глаза', 'уши', 'рот', 'нос', 'туловище']
print(1,body[3:7])
print(2,body[-3:7])
print(3,body[-5:7])
print(4,body[-5:-1])
print(5,body[-1:-5])
print(6,body[3:-1])
print(7,body[7:-1])
print(8,body)
print(9,body[:])
print(10,body[1:])
print(11,body[0:8])
print(12,body[7:0])

1 ['глаза', 'уши', 'рот', 'нос']
2 ['рот', 'нос']
3 ['глаза', 'уши', 'рот', 'нос']
4 ['глаза', 'уши', 'рот', 'нос']
5 []
6 ['глаза', 'уши', 'рот', 'нос']
7 []
8 ['голова', 'руки', 'ноги', 'глаза', 'уши', 'рот', 'нос', 'туловище']
9 ['голова', 'руки', 'ноги', 'глаза', 'уши', 'рот', 'нос', 'туловище']
10 ['руки', 'ноги', 'глаза', 'уши', 'рот', 'нос', 'туловище']
11 ['голова', 'руки', 'ноги', 'глаза', 'уши', 'рот', 'нос', 'туловище']
12 ['туловище', 'рот', 'глаза', 'руки']


2.5 Срез с шагом

In [22]:
rabbits = ['Пушок', 'Дружок', 'Мурзик', 'Барсик', 'Эдуард', 'Ушастик', 'Роджер', 'Трус']
print(1,rabbits[0:7:2])              #срез с шагом
print(2,rabbits[:7:2])   
print(3,rabbits[0::2]) 
print(4,rabbits[::2]) 
print(5,rabbits[7::-2])              #срез с отрицательным шагом, границы поменяли места
print(6,rabbits[:0:-2])
print(7,rabbits[::-2])

1 ['Пушок', 'Мурзик', 'Эдуард', 'Роджер']
2 ['Пушок', 'Мурзик', 'Эдуард', 'Роджер']
3 ['Пушок', 'Мурзик', 'Эдуард', 'Роджер']
4 ['Пушок', 'Мурзик', 'Эдуард', 'Роджер']
5 ['Трус', 'Ушастик', 'Барсик', 'Дружок']
6 ['Трус', 'Ушастик', 'Барсик', 'Дружок']
7 ['Трус', 'Ушастик', 'Барсик', 'Дружок']


Задание 1:
В ближайшее воскресенье в городе проводится выставка, в которой должны принять участие пять сотрудников фирмы. Поскольку большого желания участвовать в выставке в выходной день никто не изъявил, выбор решено было доверить компьютеру. Напишите код, который выберет из списка каждого второго сотрудника, начиная с Иванова (т.е. Иванова, Сидорова, Дятлова, Лисичкина и Капустина). Запишите свой код в одну строку без пробелов. Индексы верхней и нижней границ задайте в явном виде. Не забудьте о правильном написании имени переменной в которой хранится список

In [24]:
sparta = ['Иванов', 'Петров', 'Сидоров', 'Зайцев', 'Дятлов', 'Козлов', 'Лисичкин', 'Огурцов', 'Капустин', 'Арбузов']
sparta[0:10:2]

['Иванов', 'Сидоров', 'Дятлов', 'Лисичкин', 'Капустин']

Задание 2:
Приближается профессиональный праздник, который в данном ТОО всегда отмечают с большим размахом. К празднику руководство решило поощрить трех рядовых сотрудников. Чтобы никому не было обидно, выбор сотрудников решено было доверить компьютеру. Напишите код, с помощью которого можно извлечь из списка фамилии каждого третьего сотрудника, начиная с Петрова (т.е. Петрова, Дятлова и Огурцова). Запишите свой код в одну строку без пробелов. Индексы верхней и нижней границ задайте в явном виде. Не забудьте о правильном написании имени переменной, в которой хранится список

In [25]:
sparta = ['Иванов', 'Петров', 'Сидоров', 'Зайцев', 'Дятлов', 'Козлов', 'Лисичкин', 'Огурцов', 'Капустин', 'Арбузов']
sparta[1:10:3]

['Петров', 'Дятлов', 'Огурцов']

Задание 3:
Для создания позитивной атмосферы перед профессиональным праздником было решено украсить офис воздушными шариками. К покупке шариков решили привлечь каждого пятого сотрудника фирмы. Для удобства решили начать с первой позиции в списке (с Иванова). Напишите код, который извлекает из списка фамилии каждого пятого сотрудника, начиная с Иванова (т.е. Иванова и Козлова). Запишите свой код в одну строку без пробелов. Индексы верхней и нижней границ задайте в явном виде. Не забудьте о правильном написании имени переменной, в которой хранится список

In [28]:
sparta = ['Иванов', 'Петров', 'Сидоров', 'Зайцев', 'Дятлов', 'Козлов', 'Лисичкин', 'Огурцов', 'Капустин', 'Арбузов']
sparta[0:10:5]

['Иванов', 'Козлов']

Задание 4:
Иванов возмутился, что из-за того, что его фамилия стоит первая в списке, его постоянно включают во все мероприятия. Руководство ТОО всегда проявляло чуткость к сотрудникам, поэтому кандидатов для участия в субботнике по благоустройству территории решило выбирать не с начала списка, а с противоположной стороны. Вот код, с помощью которого были выбраны участники субботника: sparta[::-3]. Судя по результатам работы кода, кого из сотрудников ждёт продуктивная работа на свежем воздухе?

In [29]:
sparta = ['Иванов', 'Петров', 'Сидоров', 'Зайцев', 'Дятлов', 'Козлов', 'Лисичкин', 'Огурцов', 'Капустин', 'Арбузов']
sparta[::-3]

['Арбузов', 'Лисичкин', 'Зайцев', 'Иванов']

Задание 5:
Соседний с ТОО "Рога и копыта" офис арендовала команда молодых ребят - организаторов квестов. Чтобы подружиться со своими соседями, они подарили ТОО "Рога и копыта" пять бесплатных билетов на ближайший квест. Два билета забрали директор и его заместитель, а оставшиеся билеты было решено разыграть среди сотрудников. Вот код, с помощью которого были выбраны участники квеста: sparta[-2:1:-3]. Судя по результатам работы кода, кого из сотрудников ждёт весёлый вечер в компании начальства?

In [30]:
sparta = ['Иванов', 'Петров', 'Сидоров', 'Зайцев', 'Дятлов', 'Козлов', 'Лисичкин', 'Огурцов', 'Капустин', 'Арбузов']
sparta[-2:1:-3]

['Капустин', 'Козлов', 'Сидоров']

2.6 Методы для работы со списками

In [31]:
my_list = [1, 2, 3, 4, 5]          #метод Append
my_list.append(100500)
print(my_list)

[1, 2, 3, 4, 5, 100500]


In [33]:
my_list=[1,2,3]                   #аналогичное действие без использлвания метода Append
x=4
my_list[len(my_list):] = [x]
print(my_list)

[1, 2, 3, 4]


In [34]:
old_salary = [35000, 50000, 65000, 49000, 55000]
new_salary = []
for salary in old_salary:
    new_salary.append(salary * 1.9)               #создание нового списка с помощью метода Append

print(new_salary)

[66500.0, 95000.0, 123500.0, 93100.0, 104500.0]


In [35]:
my_list = [10, 65, 31, 29, 90, 87, 100]
my_list.sort()                                    #сортировка элементов списка
print(my_list)

[10, 29, 31, 65, 87, 90, 100]


In [36]:
my_list = [10, 65, 31, 29, 90, 87, 100]
my_list.sort(reverse = False)               #сортировка по возрастанию с помощью параметра reverse
print(my_list)

[10, 29, 31, 65, 87, 90, 100]


In [ ]:
my_list = [10, 65, 31, 29, 90, 87, 100]
my_list.sort(reverse = True)               #сортировка по убыванию с помощью параметра reverse
print(my_list)

In [37]:
my_list = ['банан', 'дыня', 'апельсин', 'груша', 'вишня']
my_list.sort(reverse = False)
print(my_list)

['апельсин', 'банан', 'вишня', 'груша', 'дыня']


In [38]:
my_list = ['банан', 'дыня', 'апельсин', 'груша', 'вишня']
my_list.sort(reverse = True)
print(my_list)

['дыня', 'груша', 'вишня', 'банан', 'апельсин']


In [39]:
salary = [100000, 45000, 78000, 29000, 55000, 60000]
lowest_salary = min(salary)                           #определение минимального значения
print(lowest_salary) 

29000


In [40]:
salary = [100000, 45000, 78000, 29000, 55000, 60000]
highest_salary = max(salary)                          #определение максимального значения
print(highest_salary) 

100000


In [41]:
my_friends = ['Дмитрий', 'Евгений', 'Елена', 'Михаил', 'Елена', 'Татьяна', 'Антон', 'Елена']
popular_name = my_friends.count('Елена')                  #подсчет количества элементов
print(popular_name) 

3


In [48]:
my_list = [1]
for i in range(10):
    my_list.append(my_list[i] * 2)
my_list.sort(reverse = True)
print(my_list)

[1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1]


In [52]:
fruits = 'яблоко банан апельсин баклажан перец помидор арбуз ананас'.split()
my_list = []
for fruit in fruits:
    my_list.append(fruit[0])
my_list.sort()
print(my_list)  
n=my_list.count(my_list[0]) 
print(n)

['а', 'а', 'а', 'б', 'б', 'п', 'п', 'я']
3


Задание 8:
Напишите программу, которая создаёт список, содержащий целые, кратные трём числа в интервале от 1 до 50. Найдите сумму элементов этого списка. Результат вычислений сохраните в переменной с именем result.

In [53]:
my_list=[]
result = 0
for number in range(1,51):
    if number%3==0:
        my_list.append(number)
        result=result+number
print(result)
      

408


Задание 9:
Напишите программу, которая создаёт список my_list, содержащий длины слов из списка raw_list (дан в начале кода) и находит сумму минимального и максимального элементов нового списка (my_list). Результат вычислений (сумма минимального и максимального элементов списка my_list) присвойте переменной result.

In [54]:
raw_list = ['переменные', 'циклы', 'условия', 'списки', 'словари', 'файлы', 'функции']
my_list=[]
for word in raw_list:
    my_list.append(len(word))
result=min(my_list)+max(my_list)
print(result)

15


Задание 10: 
Дан список raw_list (содержимое списка приведено в начале кода). Найдите минимальное (x_min) и максимальное (x_max) значения элементов данного списка. 
Создайте новый список my_list, состоящий из элементов списка raw_list, умноженных на x_min, если элемент является чётным числом и на x_max в случае, если элемент нечётный.
Найдите максимальное значение списка my_list. Результат присвойте переменной result.

In [3]:
raw_list = [2, 8, 10, 23, 64, 49, 11, 52, 71, 14]
x_min=min(raw_list)
x_max=max(raw_list)
my_list=[]
for word in raw_list:
    if word%2==0:
        my_list.append(word*x_min)
    else:
        my_list.append(word*x_max)
result=max(my_list)
print(result)

5041


2.7 Генераторы списков

In [9]:
my_list = [x for x in range(1, 25, 2)]
print(my_list)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


In [11]:
my_list = []
for x in range (1, 25, 2): 
    my_list.append(x)
print(my_list)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


In [13]:
my_list = [x for x in range(10, 100) if x%3 == 0 and x%5 == 0] #создаём список из двузначных чисел, кратных одновременно 3 и 5
print(my_list)

[15, 30, 45, 60, 75, 90]


In [15]:
powers = [x**y for x in range(1, 10) for y in [2,10]]  #результаты возведения чисел от 1 до 9 в квадрат и в 10 степень
print(powers)

[1, 1, 1, 4, 8, 1024, 9, 27, 59049, 16, 64, 1048576, 25, 125, 9765625, 36, 216, 60466176, 49, 343, 282475249, 64, 512, 1073741824, 81, 729, 3486784401]


In [52]:
numbers = [x for x in range(3,100) if [x%y for y in range(2,x)].count(0) == 0] #все простые числа в интервале от 3 до 100
print(numbers)

[3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


Задание 9:  
Перепишите привёденный ниже код, используя генератор списков. Полученный в результате работы генератора список должен иметь имя my_list.

In [16]:
my_list = []
for x in range(1, 50):
    if x%7 == 0:
        my_list.append(x**0.5)
print(my_list)

[2.6457513110645907, 3.7416573867739413, 4.58257569495584, 5.291502622129181, 5.916079783099616, 6.48074069840786, 7.0]


In [17]:
my_list = [x**0.5 for x in range(1, 50) if x%7 == 0] 
print(my_list)

[2.6457513110645907, 3.7416573867739413, 4.58257569495584, 5.291502622129181, 5.916079783099616, 6.48074069840786, 7.0]


Задание 10: 
Перепишите привёденный ниже код, используя генератор списков. Полученный в результате работы генератора список должен иметь имя my_list.

In [18]:
my_list = []
for x in range(90, 100):
    first_digit = x//10
    last_digit = x%10
    my_list.append(first_digit + last_digit)
print(my_list)

[9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [19]:
my_list = [x//10+x%10 for x in range(90, 100)] 
print(my_list)

[9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


2.9 Словарь

In [8]:
d = {} # то же самое, что d = dict()
d['a'] = 123
d['b'] = 345
d['c'] = 678
print(d)


{'a': 123, 'b': 345, 'c': 678}


In [9]:
d = dict()
d['a'] = 123
d['b'] = 345
d['c'] = 678
print(d)

{'a': 123, 'b': 345, 'c': 678}


In [11]:
employee_base = {
    'Мария Никитина':'+79033923029',
    'Егор Савичев':'+78125849204', 
    'Александр Пахомов':'+79053049385',
    'Алина Егорова':'+79265748370', 
    'Руслан Башаров':'+79030598495',
}
print(employee_base['Алина Егорова'])

+79265748370


In [10]:
request = ['Мария Никитина', 'Егор Савичев', 'Алексей Чернышевский']
for name in request:
    if name in employee_base:
        print(employee_base[name])
    else:
        print('Неизвестный сотрудник')

+79033923029
+78125849204
Неизвестный сотрудник


Жеребьевка Чемпионата мира-2018 
Дан словарь с результатами жеребьевки Чемпионата мира по футболу-2018 пяти стран по группам. 
Напишите код, который по названию страны country присваивает переменной group название группы по результатам жеребьевки. Если страны нет в словаре draw_dict, то переменной group должно присваивается значение 'unknown'. Выполните код для значения country = 'Италия'. 

In [13]:
draw_dict = {
    'Россия': 'A',
    'Португалия': 'B',
	'Франция': 'C',
	'Дания': 'C',
	'Египет': 'A'
}
country=input()
if country in draw_dict:
    group=draw_dict[country]
else:
    group='unknown'
print(group)

Италия
unknown


Пропущенные ключи. Метод setdefault.

In [14]:
simple_dict = {'a': 1}
simple_dict.setdefault('b', 0)  # автоматически создаст новый ключ
print(simple_dict)

{'a': 1, 'b': 0}


In [15]:
simple_dict = {'a': 1, 'b': 0}
simple_dict.setdefault('b', 5)  # значение ключа ‘b’ изменено не будет.
print(simple_dict)

{'a': 1, 'b': 0}


In [16]:
for name in request:
    employee_base.setdefault(name, 'Неизвестный сотрудник')
    print(employee_base[name])

+79033923029
+78125849204
Неизвестный сотрудник


Жеребьевка Чемпионата мира-2018 
Решите предыдущую задачу, используя метод setdefault. Вместо проверки на наличие ключа вы можете сразу назначить значение по умолчанию 'unknown'. Проверьте работу кода для country = 'Италия'. Результат запишите в переменную group

In [18]:
draw_dict = {
    'Россия': 'A',
    'Португалия': 'B',
	'Франция': 'C',
	'Дания': 'C',
	'Египет': 'A'
}
country=input()
draw_dict.setdefault(country, 'unknown')
group=draw_dict[country]
print(group)

Италия
unknown


2.12 Перебор элементов словаря.

В корпоративном справочнике имеется следующая структура должностей
employee_base = {'Мария Никитина': 'менеджер', 'Егор Савичев': 'разработчик', 'Александр Пахомов': 'дизайнер', 'Алина Егорова': 'разработчик', 'Руслан Башаров': 'верстальщик'}
Необходимо отфильтровать сотрудников в должности разработчика.

In [25]:
employee_base = {'Мария Никитина': 'менеджер', 'Егор Савичев': 'разработчик', 'Александр Пахомов': 'дизайнер', 
                 'Алина Егорова': 'разработчик', 'Руслан Башаров': 'верстальщик'}
for employee in employee_base:           # перебор ключей
    print(employee)
for employee in employee_base.keys():    # метод keys - результат тот же
    print(employee)
for employee in employee_base:           # зная в каждом шаге цикла ключ, можно вывести соответствующее значение 
    print(employee, employee_base[employee])
for employee in employee_base:
    if employee_base[employee] == 'разработчик':      # громоздко, но работает
        print(employee)
for position in employee_base.values():  # перебор значений методом values
    print(position)
i=0
for position in employee_base.values():    # удобно посчитать количество сотрудников с позицией “разработчик”
    if position == 'разработчик':
        i=i+1
print(i)
for employee, position in employee_base.items():      # перебор ключей и значений одновременно методом items 
    print(employee, position)
for employee, position in employee_base.items():     # фильтруем сотрудников в должности разработчика.
    if position == 'разработчик':
        print(employee)

Мария Никитина
Егор Савичев
Александр Пахомов
Алина Егорова
Руслан Башаров
Мария Никитина
Егор Савичев
Александр Пахомов
Алина Егорова
Руслан Башаров
Мария Никитина менеджер
Егор Савичев разработчик
Александр Пахомов дизайнер
Алина Егорова разработчик
Руслан Башаров верстальщик
Егор Савичев
Алина Егорова
менеджер
разработчик
дизайнер
разработчик
верстальщик
2
Мария Никитина менеджер
Егор Савичев разработчик
Александр Пахомов дизайнер
Алина Егорова разработчик
Руслан Башаров верстальщик
Егор Савичев
Алина Егорова


Фильтрация результатов жеребьевки:
Отфильтруйте словарь draw_dict, оставив в нем только страны группы A. Отфильтрованный результат запишите в новый словарь draw_new
Подсказка:
Для добавления в словарь нового элемента в коде нужно указать имя словаря, далее в квадратных скобках указать новый ключ (в виде строки или имени переменной), поставить знак " = " и после этого указать значение, которое необходимо установить для данного ключа.

draw_dict = {
    'Россия': 'A',
    'Португалия': 'B',
	'Франция': 'C',
	'Дания': 'C',
	'Египет': 'A'
}
draw_new={}
for country in draw_dict:
    if draw_dict[country] == 'A': 
        draw_new[country]=draw_dict[country]      
print(draw_new)

Фильтрация результатов жеребьевки 
Отфильтруйте словарь draw_dict с помощью метода items, оставив в нем только страны группы A. Отфильтрованный результат запишите в новый словарь draw_new

In [26]:
draw_dict = {
    'Россия': 'A',
    'Португалия': 'B',
	'Франция': 'C',
	'Дания': 'C',
	'Египет': 'A'
}
draw_new={}
for country, result in draw_dict.items():     
    if result == 'A':
        draw_new[country]=draw_dict[country]    
print(draw_new)

{'Россия': 'A', 'Египет': 'A'}


2.16 Задачи на структуру словарей

Задание 1
Сотрудник ведет запись ежедневных расходов по партнерам. Он мог бы записывать суммы за 1-3 апреля в знакомые нам списки, но это не очень удобно: [2504, 4994, 6343]. Оформите расходы в словарь, в котором ключами являются даты ('2019-04-01', '2019-04-02', '2019-04-03' апреля), а значениями - суммы расходов (2504, 4994 и 6343 рублей соответственно).

In [31]:
charges=[2504, 4994, 6343]
dates=['2019-04-01', '2019-04-02', '2019-04-03']
my_dict={}
for i in range (0,3):
    my_dict.setdefault(dates[i],charges[i])
print(my_dict)    

{'2019-04-01': 2504, '2019-04-02': 4994, '2019-04-03': 6343}


Задание 2 
Посчитайте сумму расходов из словаря первой задачи

In [34]:
i=0
for charge in my_dict.values():
    i=i+charge
print(i)

13841


Задание 3 
Имеется база служебных телефонов сотрудников.
Поступил запрос на проверку корректности номера сотрудника Кузнецовой Дарьи: если ее номер в базе равен 5142, то вывести на экран “Номер верен”. Какой из перечисленных вариантов кода делает эту операцию?

In [37]:
phones = {
	'Гордиенко Виктория': 5140,
	'Анисимов Кирилл': 5145,
	'Кузнецова Дарья': 5142
}
if phones['Кузнецова Дарья'] == 5142:
	print('Номер верен')
for name, phone in phones.items():
	if name == 'Кузнецова Дарья' and phone == 5142:
		print('Номер верен')
for record in phones:
	if record == 'Кузнецова Дарья' and phones[record] == 5142:
		print('Номер верен')

Номер верен
Номер верен
Номер верен


2.17 Вложенные списки

Рассмотрим простой пример: имеется CSV-файл со товарными позициями интернет-магазина. В первом столбце идентификатор товара, во втором - название, в третьем - количество штук на складе. При чтении такого файла получим следующую структуру:

In [40]:
csv_file = [
    ['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9],
    ['100728', 'Скейтборд Jdbug RT03', 32],
    ['100732', 'Роллерсерф Razor RipStik Bright', 11],
    ['100803', 'Ботинки для сноуборда DC Tucknee', 20],
    ['100898', 'Шагомер Omron HJA-306', 2],
    ['100934', 'Пульсометр Beurer PM62', 17],
]
print(csv_file[4])   # берем из этой "базы" количество шагомеров
print(csv_file[4][2])

['100898', 'Шагомер Omron HJA-306', 2]
2


Получение идентификатора товара 
Напишите код, который записывает в переменную pulsometer_id идентификатор товара "Пульсометр Beurer PM62"

In [44]:
csv_file = [
    ['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9],
    ['100728', 'Скейтборд Jdbug RT03', 32],
    ['100732', 'Роллерсерф Razor RipStik Bright', 11],
    ['100803', 'Ботинки для сноуборда DC Tucknee', 20],
    ['100898', 'Шагомер Omron HJA-306', 2],
    ['100934', 'Пульсометр Beurer PM62', 17],
]
pulsometer_id=csv_file[5][0]
print(pulsometer_id)

100934


2.18 Проход по вложенному списку

In [45]:
for record in csv_file:
    print(record)
for record in csv_file:
    if record[1] == 'Шагомер Omron HJA-306':
        print('Количество шагомеров на складе - {}шт'.format(record[2]))

['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9]
['100728', 'Скейтборд Jdbug RT03', 32]
['100732', 'Роллерсерф Razor RipStik Bright', 11]
['100803', 'Ботинки для сноуборда DC Tucknee', 20]
['100898', 'Шагомер Omron HJA-306', 2]
['100934', 'Пульсометр Beurer PM62', 17]


Фильтрация товарных позиций по количеству.
Отфильтруйте список товарных позиций csv_file, оставив только те позиции, у которых количество штук на складе больше 10. Результат запишите в переменную csv_file_filtered

In [48]:
csv_file = [
    ['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9],
    ['100728', 'Скейтборд Jdbug RT03', 32],
    ['100732', 'Роллерсерф Razor RipStik Bright', 11],
    ['100803', 'Ботинки для сноуборда DC Tucknee', 20],
    ['100898', 'Шагомер Omron HJA-306', 2],
    ['100934', 'Пульсометр Beurer PM62', 17],
]
csv_file_filtere=[]
for record in csv_file:
    if record[2]>10:
        csv_file_filtere.append(record)
print(csv_file_filtere)

[['100728', 'Скейтборд Jdbug RT03', 32], ['100732', 'Роллерсерф Razor RipStik Bright', 11], ['100803', 'Ботинки для сноуборда DC Tucknee', 20], ['100934', 'Пульсометр Beurer PM62', 17]]


In [ ]:
my_list=[1,2,3]                   #аналогичное действие без использлвания метода Append
x=4
my_list[len(my_list):] = [x]
print(my_list)

In [53]:
csv_file = [
    ['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9],
    ['100728', 'Скейтборд Jdbug RT03', 32],
    ['100732', 'Роллерсерф Razor RipStik Bright', 11],
    ['100803', 'Ботинки для сноуборда DC Tucknee', 20],
    ['100898', 'Шагомер Omron HJA-306', 2],
    ['100934', 'Пульсометр Beurer PM62', 17],
]
csv_file_filtere=[record for record in csv_file if record[2]>10]
print(csv_file_filtere)

[['100728', 'Скейтборд Jdbug RT03', 32], ['100732', 'Роллерсерф Razor RipStik Bright', 11], ['100803', 'Ботинки для сноуборда DC Tucknee', 20], ['100934', 'Пульсометр Beurer PM62', 17]]


In [54]:
csv_file = [
    ['100412', 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 9],
    ['100728', 'Скейтборд Jdbug RT03', 32],
    ['100732', 'Роллерсерф Razor RipStik Bright', 11],
    ['100803', 'Ботинки для сноуборда DC Tucknee', 20],
    ['100898', 'Шагомер Omron HJA-306', 2],
    ['100934', 'Пульсометр Beurer PM62', 17],
]
csv_file_filtere=[]
for record in csv_file:
    if record[2]>10:
        csv_file_filtere.append(record[1])
print(csv_file_filtere)

['Скейтборд Jdbug RT03', 'Роллерсерф Razor RipStik Bright', 'Ботинки для сноуборда DC Tucknee', 'Пульсометр Beurer PM62']


2.19 Вложенные словари

In [56]:
contacts = {
    'Борискин Владимир': {
        'tel': '5387',
        'position': 'менеджер'
    },
    
    'Сомова Наталья': {
        'tel': '5443',
        'position': 'разработчик'
    },
}
print(contacts['Борискин Владимир'])     #Для получения телефона сначала обращаемся к ключу по имени сотрудника
print(contacts['Борискин Владимир']['tel'])     #для получения номера телефона в полученном словаре обращаемсяся к ключу tel

{'tel': '5387', 'position': 'менеджер'}
5387


Фильтрация товарных словарей.
Разработчики поменяли формат выгрузки из базы данных товарных позиций. Теперь это список словарей, каждый столбец в котором имеет имя. Напишите код, который оставляет только те товары, в названии которых есть слово "Ботинки". Результат запишите в переменную csv_dict_boots

In [62]:
csv_dict = [
    {'id': '100412', 'position': 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 'count': 9},
    {'id': '100728', 'position': 'Скейтборд Jdbug RT03', 'count': 32},
    {'id': '100732', 'position': 'Роллерсерф Razor RipStik Bright', 'count': 11},
    {'id': '100803', 'position': 'Ботинки для сноуборда DC Tucknee', 'count': 20},
    {'id': '100898', 'position': 'Шагомер Omron HJA-306', 'count': 2},
    {'id': '100934', 'position': 'Пульсометр Beurer PM62', 'count': 17},
]
csv_dict_boots=[]
for my_dict in csv_dict:
    for my_key in my_dict:
        if my_key=='position':
            if "Ботинки" in my_dict[my_key]:
                csv_dict_boots.append(my_dict)
print(csv_dict_boots)    
    

[{'id': '100412', 'position': 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 'count': 9}, {'id': '100803', 'position': 'Ботинки для сноуборда DC Tucknee', 'count': 20}]


In [67]:
csv_dict = [
    {'id': '100412', 'position': 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 'count': 9},
    {'id': '100728', 'position': 'Скейтборд Jdbug RT03', 'count': 32},
    {'id': '100732', 'position': 'Роллерсерф Razor RipStik Bright', 'count': 11},
    {'id': '100803', 'position': 'Ботинки для сноуборда DC Tucknee', 'count': 20},
    {'id': '100898', 'position': 'Шагомер Omron HJA-306', 'count': 2},
    {'id': '100934', 'position': 'Пульсометр Beurer PM62', 'count': 17},
]
csv_dict_boots=[]
for my_dict in csv_dict:
    if "Ботинки" in my_dict['position']:
        csv_dict_boots.append(my_dict)
print(csv_dict_boots)    

[{'id': '100412', 'position': 'Ботинки для горных лыж ATOMIC Hawx Prime 100', 'count': 9}, {'id': '100803', 'position': 'Ботинки для сноуборда DC Tucknee', 'count': 20}]


Задание 2 
Дана статистика результатов рекламной кампании по каналу (ключ 'source') и сумме расходов ('cost').
Напишите код, который ищет минимальное значение ключа cost в этом словаре. Укажите это значение в качестве ответа.

In [69]:
results = [
	{'cost': 98, 'source': 'vk'},
	{'cost': 153, 'source': 'yandex'},
	{'cost': 110, 'source': 'facebook'},
]
check=[]
for my_dict in results:
    check.append(my_dict['cost'])
print(min(check))

98


Задание 3 
На каждом этапе производственной линии закладываются отклонения от исходных размеров, ведущие к деформации. Т. е. после каждого этапа размер детали умножается на значение ключа damage.
Если исходный размер детали принять за 100%, то на каком шаге повреждения приведут к размеру менее 90%?

In [77]:
defect_stats = [
	{'step number': 1, 'damage': 0.98},
	{'step number': 2, 'damage': 0.99},
	{'step number': 3, 'damage': 0.99},
	{'step number': 4, 'damage': 0.96},
	{'step number': 5, 'damage': 0.97},
	{'step number': 6, 'damage': 0.97},
]
size=1
for step in defect_stats:
    size=size*step['damage']
    if size<0.9:
        print(step['step number'])
        break
    
   

5


Задание 4 
Имеется статистика курсов валют. Какая валюта имеет минимальный курс по отношению к рублю за 1 единицу? Для определения курса валюты необходимо значение ключа 'Value' разделить на значение ключа 'Nominal'. В качестве ответа укажите код валюты (например, AUD)

In [83]:
currency = {
	'AMD': {
		'Name': 'Армянских драмов',
		'Nominal': 100,
		'Value': 13.121
	},

	'AUD': {
		'Name': 'Австралийский доллар',
		'Nominal': 1,
		'Value': 45.5309
	},

	'INR': {
		'Name': 'Индийских рупий',
		'Nominal': 100,
		'Value': 92.9658
	},

	'MDL': {
		'Name': 'Молдавских леев',
		'Nominal': 10,
		'Value': 36.9305
	},
}
min_rate=10000
for the_currency in currency:
    rate=currency[the_currency]['Value']/currency[the_currency]['Nominal']
    if rate<min_rate:
        min_rate=rate
        min_currency=the_currency
print(min_currency)   

AMD


Задание 5 
Согласно сайту www.bodycounters.com в четырех частях фильма “Пираты Карибского моря” было довольно много погибших. 
Есть их статистика.
Напишите скрипт, который считает общее число погибших во всех сериях.
Укажите итоговое число в качестве ответа.

In [87]:
bodycount = {
	'Проклятие Черной жемчужины': {
		'человек': 17
	}, 

	'Сундук мертвеца': {
		'человек': 56,
		'раков-отшельников': 1
	},

	'На краю света': {
		'человек': 88
	},

	'На странных берегах': {
		'человек': 56,
		'русалок': 2,
		'ядовитых жаб': 3,
		'пиратов зомби': 2
	}
}
all_dead=0
for part in bodycount:
    for dead in bodycount[part].values():    
        all_dead=all_dead+dead
print(all_dead)


225


In [94]:
arrivals = {
	'Париж': {'время': '15:25', 'статус': 'ожидается', 'рейс': ['Аэрофлот']},
	'Пекин': {'время': '15:35', 'статус': 'опаздывает', 'рейс': ['China Southern Airlines', 'Россия']},
	'Лиссабон': {'время': '15:40', 'статус': 'ожидается', 'рейс': ['Nordwind', 'Аэрофлот']},
}
print(len(arrivals['Пекин']['рейс']))

2


2.24 Открытие файла в Python

In [96]:
import json                              # использум библиотеку json
with open('data.json', 'rb') as infile:
    data = json.load(infile)
type(data)                              # определяем тип файла  - это словарь

dict

In [97]:
data.keys()             # смотрим ключи этого словаря - он всего один

dict_keys(['events_data'])

In [98]:
data['events_data']    # смотрим значение по этому ключу - это список из словарей

[{'id': 47946124,
  'client_id': 62526,
  'user_id': 110777,
  'category': 'page',
  'action': 'enter',
  'options': {'name': 'landing'}},
 {'id': 47947076,
  'client_id': 61944,
  'user_id': 108565,
  'category': 'page',
  'action': 'enter',
  'options': {'name': 'landing'}},
 {'id': 47962056,
  'client_id': 27115,
  'user_id': 49440,
  'category': 'page',
  'action': 'enter',
  'options': {'name': 'page'}},
 {'id': 47962120,
  'client_id': 27115,
  'user_id': 49440,
  'category': 'datepicker',
  'action': 'apply',
  'options': {'endDate': '2019-03-31 23:59:59',
   'startDate': '2019-03-25 00:00:00'}},
 {'id': 47962218,
  'client_id': 27115,
  'user_id': 49440,
  'category': 'table',
  'action': 'sort',
  'options': {'dir': 'ASC', 'name': 'deal_date'}},
 {'id': 47962238,
  'client_id': 27115,
  'user_id': 49440,
  'category': 'table',
  'action': 'sort',
  'options': {'dir': 'DESC', 'name': 'deal_date'}},
 {'id': 47962532,
  'client_id': 27115,
  'user_id': 49440,
  'category': 'table

2.25 Работа с данными

Анализ данных с помощью использования словарей и списков.

In [99]:
data_list = data['events_data']  # для удобства запишем этот список в новую переменную, чтоб не обращаться по ключу
print(len(data_list))            # считаем количество событий - длину списка

107


In [100]:
categories = []
for item in data_list:
    category = item['category']
    categories.append(category)  # запишем в новый список все встречающиеся категории (ключ 'category') - что за события?
print (categories)               # чаще всего встречается категория 'page', означающая просмотр страницы

['page', 'page', 'page', 'datepicker', 'table', 'table', 'table', 'table', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'report', 'report', 'report', 'report', 'page', 'report', 'page', 'page', 'page', 'table', 'table', 'table', 'table', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'report', 'page', 'page', 'page', 'page', 'page', 'report', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'datepicker', 'page', 'page', 'page', 'page', 'page', 'page', 'report', 'table', 'table', 'datepicker', 'datepicker', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page', 'page']


In [105]:
import collections
c = collections.Counter()
for category in categories:
    c[category] += 1
print (c)

Counter({'page': 74, 'datepicker': 15, 'table': 10, 'report': 8})


In [102]:
import collections
c = collections.Counter()          # считает количество неизменяемых элементов 
for word in ['spam', 'egg', 'spam', 'counter', 'counter', 'counter']:
    c[word]=c[word]+1
print(c)
print(c['counter'])
print(c['collections'])

Counter({'counter': 3, 'spam': 2, 'egg': 1})
3
0


2.26 Анализируем данные

In [110]:
table_clients = []             
for item in data_list:                     # пройдемся по каждому словарю из списка data_list 
    client_id = item['client_id']
    category = item['category']
    if category == 'table':                #  новый список table_clients - показывает какие клиенты совершают события table
        table_clients.append(client_id)
print (table_clients)

[27115, 27115, 27115, 27115, 60459, 60459, 60459, 60459, 58113, 58113]


In [111]:
c = collections.Counter()
for table_client in table_clients:
    c[table_client] += 1            # считаем, кто из клиентов сколько раз совершал действие 'table'
print (c)                           # видим, что у нас всего 3 пользователя, два из которых совершили по 4 действия

Counter({27115: 4, 60459: 4, 58113: 2})


In [112]:
print (len(c.keys()))               # считаем количество пользователей

3


In [113]:
print(c[27115])    # можно вывести информацию по конкретному пользователю, обратившись по соответствующему ключу

4


Задание 1.
Подсчитайте количество клиентов (client_id), которые совершали какие-либо действия

In [136]:
clients = []
for item in data_list:
    client = item['client_id']
    clients.append(client)       # создаю список из всех элементов, у которых был ключом "client_id"
import collections
c = collections.Counter()
for client in clients:
    c[client] += 1              # создаю словарь c, считающий число одинаковых элементов (пары - client_id:количество)
client_id=len(c.keys())         # считаю количество ключей в этом словаре
print (client_id) 

Counter({60459: 12, 27115: 11, 62602: 11, 56544: 8, 58113: 7, 18923: 5, 23207: 4, 52492: 3, 24500: 2, 53666: 2, 41737: 2, 62526: 1, 61944: 1, 62017: 1, 63120: 1, 59883: 1, 2913: 1, 62940: 1, 63149: 1, 45391: 1, 63019: 1, 15759: 1, 62007: 1, 62941: 1, 51009: 1, 62236: 1, 44682: 1, 39709: 1, 62144: 1, 25301: 1, 33645: 1, 62089: 1, 26705: 1, 1103: 1, 62439: 1, 44196: 1, 50149: 1, 57009: 1, 57207: 1, 32792: 1, 27323: 1, 58330: 1, 61245: 1, 19799: 1, 48128: 1, 57613: 1, 61244: 1, 53018: 1, 61078: 1, 20820: 1, 49700: 1})
51
12


Задание 2.
Сколько действий совершил клиент (client_id) под номером 60459?

In [137]:
clients = []
for item in data_list:
    client = item['client_id']
    clients.append(client)       # создаю список из всех элементов, у которых был ключом "client_id"
import collections
c = collections.Counter()
for client in clients:
    c[client] += 1              # создаю словарь c, считающий число одинаковых элементов (пары - client_id:количество) 
print(c[60459])    

12


Задание 3. 
Сколько действий с категорией (category) = page совершил клиент под номером 62602?

In [133]:
client =62602
acts=0
for item in data_list:
    if item['client_id']==client and item['category']=='page':
        acts=acts+1
print(acts)

9


Задание 4.
Сколько уникальных клиентов совершили действия с категорией (category) = report?

In [138]:
client_reports=[]
for item in data_list:
    if item['category']=='report':
        client_reports.append(item['client_id'])  # создаю список из client_id тех, кто совершил report
import collections
c = collections.Counter()
for client in client_reports:
    c[client] += 1
print (len(c.keys()))

Counter({60459: 5, 62602: 2, 58113: 1})
3


Дополнительное задание 5.
Перечислите в каждом из полей идентификаторы клиентов, которые совершили действия с категорией (category) = report (В порядке возрастания)

In [139]:
print(c)

Counter({60459: 5, 62602: 2, 58113: 1})
